window:
  opacity: 0.5
  dynamic_padding: true

font:
  normal:
    family: Hack Nerd Font Mono 
    style: Regular
  
  bold:
    family: Hack Nerd Font Mono
    style: bold

  italic:
    family: Hack Nerd Font Mono
    style: Italic
  
  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic

  size: 10

colors: 
  # Default colors
  primary:
    background: "#000000"

  normal:
      black:   '#32344a'
      red:     '#f7768e'
      green:   '#9ece6a'
      yellow:  '#e0af68'
      blue:    '#7aa2f7'
      magenta: '#ad8ee6'
      cyan:    '#449dab'
      white:   '#787c99'

    # Bright colors
  bright:
      black:   '#444b6a'
      red:     '#ff7a93'
      green:   '#b9f27c'
      yellow:  '#ff9e64'
      blue:    '#7da6ff'
      magenta: '#bb9af7'
      cyan:    '#0db9d7'
      white:   '#acb0d0'


key_bindings:
  - { key: Return, mods: Control, action: SpawnNewInstance }
  - { key: F11, action: ToggleFullscreen }
commands:
  - { name: SpawnNewInstance, command: alacritty --working-directory "$(pwd)" & disown }
